version: "3.8"
services:
  blockchain:
    build: ./randnote-blockchain
    container_name: blockchain_container
    ports:
      - '8034:8034'
    volumes:
      - ./randnote-blockchain:/blockchain #mapping local relative path to path on container
      - /blockchain/node_modules
  backend:
    depends_on:
      - mysql
    build: ./randnotex-backend
    container_name: backend_container
    ports:
      - '8024:8024'
    volumes:
      - ./randnotex-backend:/backend
      - /randnotex-backend/node_modules
    environment:
      - HOST=mysql
      - PORT=3307
      - USER=root
      - PASSWORD=5308danielromeo
      - DB=randnotex
    # command: ["./wait-for-it.sh", "mysql:3306"]

  mysql:
    image: mysql:5.7
    restart: always
    expose:
      - 3307
    ports: 
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=5308danielromeo
      - MYSQL_USER=danielromeo
      - MYSQL_PASSWORD=5308danielromeo
      - MYSQL_DATABASE=randnotex
    container_name: mysql-database
  # frontend:
  #   build: ./randnote-exchange
  #   container_name: frontend
  #   ports:
  #     - '3002:3002'
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - ./randnote-exchange:/frontend
  #     - /randnote-exchange/node_modules