// This file is designed to get the users from the backend db and allocate blockchain funds to them....
// For this to work, randnotex-backend needs to be serving.

// get all the users in the database via get req to randnotex-backend...

import Axios from "axios";

const getAutoGeneratedUsers = () =>{
    Axios.get(`http://localhost:8024/userfindAutoGens`).then(
		async (response: any) => {
            console.log(response.data); // should return all the auto generated users along with their addresses...
        }
    )
}

getAutoGeneratedUsers();